UMAP_SETTINGS:
  LD_COLUMNS: [ 'z0', 'z1', 'z2']
  NUM_COMPONENTS: 2
  #NUM_NEIGHBORS: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
  NUM_NEIGHBORS: [1000]
  MIN_DISTANCE: [0.1]

DATA:
  FILE_PATH: 'D:/Ashley_ML/machineLearningResearch/matlab_code/embedded2Dcircle.csv' #50000 Epochs

  CLASSES: ['F16', 'A10', 'B52', 'C5']
  SUPERCLASSES: ["RW", "VW"]
  CLASS_MAP: { 'F16': 0, 'A10': 1, 'B52': 2, 'C5': 3 }
  SUPERCLASS_MAP: {"RW": 0, "VW": 1}
  CLASS_DICT: { "RW": { "F16": { 'x': [ ], 'y': [ ], 'z': [ ] },
                        "A10": { 'x': [ ], 'y': [ ], 'z': [ ] },
                        "B52": { 'x': [ ], 'y': [ ], 'z': [ ] },
                        "C5": { 'x': [ ], 'y': [ ], 'z': [ ] } },
                "VW": { "F16": { 'x': [ ], 'y': [ ], 'z': [ ] },
                        "A10": { 'x': [ ], 'y': [ ], 'z': [ ] },
                        "B52": { 'x': [ ], 'y': [ ], 'z': [ ] },
                        "C5": { 'x': [ ], 'y': [ ], 'z': [ ] } }
  }
  SUPERCLASS_DICT: {"RW": {'x':[], 'y':[], 'z':[]}, "VW": {'x':[], 'y':[], 'z':[]}}