UMAP_SETTINGS:
  LD_COLUMNS: [ 'z0', 'z1', 'z2', 'z3', 'z4', 'z5', 'z6', 'z7',
                'z8', 'z9', 'z10', 'z11', 'z12', 'z13', 'z14', 'z15',
                'z16', 'z17', 'z18', 'z19', 'z20', 'z21', 'z22', 'z23',
                'z24', 'z25', 'z26', 'z27', 'z28', 'z29', 'z30', 'z31' ]
  #NUM_COMPONENTS: 3
  NUM_COMPONENTS: 32
  #NUM_NEIGHBORS: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
  NUM_NEIGHBORS: [50]
  MIN_DISTANCE: [0.05]

DATA:

  #FILE_PATH = 'D:/Ashley_ML/VAE/VAE/VAE_logs/20210730T0039/results_20210730T0150/20210730T0150dataFrame.csv' #first IR for

    # first IR UMAP: B52 only
  #FILE_PATH: 'D:/Ashley_ML/VAE/logs/fit/20211115T1754/results_20211116T1717/20211116T1717dataFrame_v2.csv'
  #FILE_PATH: 'D:/Ashley_ML/VAE/logs/fit/20211117T1438/results_20211118T1127/20211118T1127dataFrame.csv' #5000 Epochs
  #FILE_PATH: 'D:/Ashley_ML/VAE/logs/fit/20211128T2322/results_20211129T0043/20211129T0043dataFrame.csv' #1500 Epochs
  #FILE_PATH: 'D:/Ashley_ML/VAE/logs/fit/20211201T1724/results_20211201T2105/20211201T2105dataFrame.csv' #500 Epochs
  FILE_PATH: 'D:/Ashley_ML/VAE/logs/fit/20211207T1303/results_20211210T1038/20211210T1038dataFrame.csv' #50000 Epochs
  #FILE_PATH: 'D:/Ashley_ML/VAE/logs/fit/20211216T1819/results_20211216T1829/20211216T1829dataFrame.csv' #Beta_VAE
  CLASSES: ['F16', 'A10', 'B52', 'C5']
  SUPERCLASSES: ["RW", "VW"]
  CLASS_MAP: { 'F16': 0, 'A10': 1, 'B52': 2, 'C5': 3 }
  SUPERCLASS_MAP: {"RW": 0, "VW": 1}
  CLASS_DICT: { "RW": { "F16": { 'x': [ ], 'y': [ ], 'z': [ ] },
                        "A10": { 'x': [ ], 'y': [ ], 'z': [ ] },
                        "B52": { 'x': [ ], 'y': [ ], 'z': [ ] },
                        "C5": { 'x': [ ], 'y': [ ], 'z': [ ] } },
                "VW": { "F16": { 'x': [ ], 'y': [ ], 'z': [ ] },
                        "A10": { 'x': [ ], 'y': [ ], 'z': [ ] },
                        "B52": { 'x': [ ], 'y': [ ], 'z': [ ] },
                        "C5": { 'x': [ ], 'y': [ ], 'z': [ ] } }
  }
  SUPERCLASS_DICT: {"RW": {'x':[], 'y':[], 'z':[]}, "VW": {'x':[], 'y':[], 'z':[]}}