UMAP_SETTINGS:
  LD_COLUMNS: ['z0', 'z1', 'z2', 'z3', 'z4', 'z5', 'z6', 'z7',
  'z8', 'z9', 'z10', 'z11', 'z12', 'z13', 'z14', 'z15',
  'z16', 'z17', 'z18', 'z19', 'z20', 'z21', 'z22', 'z23',
  'z24', 'z25', 'z26', 'z27', 'z28', 'z29', 'z30', 'z31']
  NUM_COMPONENTS: 32
  NUM_NEIGHBORS: [5]
  MIN_DISTANCE: [0.001]

DATA:
  FILE_PATH:  'data/example_dataFrame.csv'
  IMAGE_PATH: 'imgs/'
  CLASSES: ["Plane", "Glider", "Kite", "Quadcopter", "Eagle"]
  SUPERCLASSES: ["RW", "VW"]
  CLASS_MAP: {"Plane": 0, "Glider": 1, "Kite": 2, "Quadcopter":3, "Eagle":4}
  SUPERCLASS_MAP: {"RW": 0, "VW": 1}
  CLASS_DICT: { "RW": {"Plane": {'x': [], 'y': [], 'z': []},
                               "Glider": {'x': [], 'y': [], 'z': []},
                               "Kite": {'x': [], 'y': [], 'z': []},
                               "Quadcopter": {'x': [], 'y': [], 'z': []},
                               "Eagle": {'x': [], 'y': [], 'z': []}},
                        "VW": {"Plane": {'x': [], 'y': [], 'z': []},
                              "Glider":{'x': [], 'y': [], 'z': []},
                              "Kite": {'x': [], 'y': [], 'z': []},
                              "Quadcopter": {'x': [], 'y': [], 'z': []},
                              "Eagle": {'x': [], 'y': [], 'z': []}}
                       }
  SUPERCLASS_DICT: {"RW": {'x':[], 'y':[], 'z':[]}, "VW": {'x':[], 'y':[], 'z':[]}}
